{{- if .Values.build.auth.git.username }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-build-bot
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - jenkins.io
  resources:
  - pipelineactivities
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - jenkins.io
  resources:
  - pipelineactivities
  verbs:
  - get
  - create
  - update
- apiGroups:
  - jenkins.io
  resources:
  - environments
  verbs:
  - list
  - get
{{- end }}